Module: simplify is_object checks
object::Binary has isObject method, which can be used to check whether
it is an object::ObjectFile. Use that, since dyn_casting of
object::Binary is not allowed in newer LLVMs:
lib/Module/ModuleUtil.cpp:304:78: error: cannot convert ‘llvm::object::ObjectFile’ to ‘llvm::object::ObjectFile*’ in initialization
     else if (object::ObjectFile *o = dyn_cast<object::ObjectFile>(child.get()))
                                                                              ^

Signed-off-by: Jiri Slaby <jirislaby@gmail.com>