llvm: rename ExitOnError to OptExitOnError
ExitOnError collides with llvm::ExitOnError from LLVM 4:
tools/klee/main.cpp:430:23: error: reference to 'ExitOnError' is ambiguous
  if (errorMessage && ExitOnError) {
                      ^
/usr/include/llvm/Support/Error.h:938:7: note: candidate found by name lookup is 'llvm::ExitOnError'
class ExitOnError {
      ^
klee/tools/klee/main.cpp:141:3: note: candidate found by name lookup is '(anonymous namespace)::ExitOnError'
  ExitOnError("exit-on-error",
  ^
1 error generated.

Signed-off-by: Jiri Slaby <jirislaby@gmail.com>